# This is a GitHub Action workflow to build and deploy SamKenX-INE-LX2r

name: SamKenX-INE-LX2r 

on: 

  push:

    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up JDK 1.8

      uses: actions/setup-java@v1

      with:

        java-version: 1.8

    - name: Build with Maven

      run: mvn -B package

    - name: Upload artifact

      uses: actions/upload-artifact@v1

      with:

        name: SamKenX-INE-LX2r

        path: target/*.jar

deploy:

  needs: build

  runs-on: ubuntu-latest

  steps:

  - name: Deploy to server

    run: deploy.sh

    env:

      SERVER_IP: ${{ secrets.SERVER_IP }}

      SERVER_USER
